UniversityManagementSystem/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empID { get; set; }
        public string empName { get; set; }
        public string empGender { get; set; }
        public string empNationality { get; set; }
        public string empIdentificationNo { get; set; }
        public string empPassportNo { get; set; }
        public string empBankAccount { get; set; }
        public string empAddress { get; set; }
        public string empEmail { get; set; }
        public string empPrivateAddress { get; set; }
        public string empEmergencyPhone { get; set; }
        public Nullable<System.DateTime> empDataOfBirth { get; set; }
        public string empPlaceOfBirth { get; set; }
        public string empMaritalStatus { get; set; }
        public string empPicture { get; set; }
        public string UserID { get; set; }
        public int EmpTId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EmpType EmpType { get; set; }
    }
}

UniversityManagementSystem/Areas/HRModule/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Models;
using UniversityManagementSystem.Areas.HRModule.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;

namespace UniversityManagementSystem.Areas.HRModule.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private UniversityManagementSystemEntities db = new UniversityManagementSystemEntities();

        // GET: HRModule/Employees
        public ActionResult Index()
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";
            var employees = db.Employees.Include(e => e.AspNetUser);
            return View(employees.ToList());
        }

        // GET: HRModule/Employees/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: HRModule/Employees/Create
        public ActionResult Create()
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";
            List<string> Gender = new List<string>();
            Gender.Add("male");
            Gender.Add("female");
            Gender.Add("Other");
            ViewBag.Gender = Gender.ToList();
            List<string> SocialStatus = new List<string>();
            SocialStatus.Add("Unmarried");
            SocialStatus.Add("Married");
            ViewBag.SocialStatus = SocialStatus;

            List<EmpType> empType = db.EmpTypes.ToList();
            ViewBag.empType = new SelectList(empType, "EmpTId", "EmpTName");
            //ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeModel model)
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";
            List<string> Gender = new List<string>();
            Gender.Add("male");
            Gender.Add("female");
            Gender.Add("Other");
            ViewBag.Gender = Gender.ToList();
            List<string> SocialStatus = new List<string>();
            SocialStatus.Add("Unmarried");
            SocialStatus.Add("Married");
            ViewBag.SocialStatus = SocialStatus;

            List<EmpType> empType = db.EmpTypes.ToList();
            ViewBag.empType = new SelectList(empType, "EmpTId", "EmpTName");
            if (ModelState.IsValid)
            {
                ApplicationDbContext dbUser = new ApplicationDbContext();
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(dbUser));
                var UserAdmin = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbUser));
                var User = new ApplicationUser();
                User.Email = model.Email;
                User.UserName = model.UserName;
                var check = UserAdmin.Create(User, model.Password);
                if (check.Succeeded)
                {
                    string appFeilName = Path.GetFileNameWithoutExtension(model.empPicture.FileName);
                    string extension = Path.GetExtension(model.empPicture.FileName);
                    appFeilName = model.empName + DateTime.Now.ToString("yymmssfff") + extension;
                    string PDFName = appFeilName;
                    appFeilName = Path.Combine(Server.MapPath("~/Attachments/"), appFeilName);
                    model.empPicture.SaveAs(appFeilName);
                   
                    Employee emp = new Employee();
                    emp.UserID = User.Id;
                    emp.empPicture = PDFName;
                    emp.empAddress = model.empAddress;
                    emp.empBankAccount = model.empBankAccount;
                    emp.empDataOfBirth = model.empDataOfBirth;
                    emp.empEmail = model.Email;
                    emp.empEmergencyPhone = model.empEmergencyPhone;
                    emp.empGender = model.empGender;
                    emp.empIdentificationNo = model.empIdentificationNo;
                    emp.empMaritalStatus = model.empMaritalStatus;
                    emp.empName = model.empName;
                    emp.empNationality = model.empNationality;
                    emp.empPassportNo = model.empPassportNo;
                    emp.empPlaceOfBirth = model.empPlaceOfBirth;
                    emp.empPrivateAddress = model.empPrivateAddress;
                    emp.EmpTId = model.EmpTId;
                    db.Employees.Add(emp);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                    
            }
            return View(model);
        }

        // GET: HRModule/Employees/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";
            List<string> Gender = new List<string>();
            Gender.Add("male");
            Gender.Add("female");
            Gender.Add("Other");
            ViewBag.Gender = Gender.ToList();
            List<string> SocialStatus = new List<string>();
            SocialStatus.Add("Unmarried");
            SocialStatus.Add("Married");
            ViewBag.SocialStatus = SocialStatus;

            List<EmpType> empType = db.EmpTypes.ToList();
            ViewBag.empType = new SelectList(empType, "EmpTId", "EmpTName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee model = db.Employees.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            EmployeeModel emp = new EmployeeModel();
            emp.empID = model.empID;
            emp.UserID = model.UserID;
            emp.empAddress = model.empAddress;
            emp.empBankAccount = model.empBankAccount;
            emp.empDataOfBirth =Convert.ToDateTime( model.empDataOfBirth);
            emp.EmpTId = model.EmpTId;
            emp.empEmergencyPhone = model.empEmergencyPhone;
            emp.empGender = model.empGender;
            emp.empIdentificationNo = model.empIdentificationNo;
            emp.empMaritalStatus = model.empMaritalStatus;
            emp.empName = model.empName;
            emp.empNationality = model.empNationality;
            emp.empPassportNo = model.empPassportNo;
            emp.empPlaceOfBirth = model.empPlaceOfBirth;
            emp.empPrivateAddress = model.empPrivateAddress;
            

            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeModel model)
        {
            ViewBag.MainTitle = "HR Module";
            ViewBag.SubTitle = "Employee ";
            List<string> Gender = new List<string>();
            Gender.Add("male");
            Gender.Add("female");
            Gender.Add("Other");
            ViewBag.Gender = Gender.ToList();
            List<string> SocialStatus = new List<string>();
            SocialStatus.Add("Unmarried");
            SocialStatus.Add("Married");
            ViewBag.SocialStatus = SocialStatus;

            List<EmpType> empType = db.EmpTypes.ToList();
            ViewBag.empType = new SelectList(empType, "EmpTId", "EmpTName");
            if (ModelState.IsValid)
            {
                string appFeilName = Path.GetFileNameWithoutExtension(model.empPicture.FileName);
                string extension = Path.GetExtension(model.empPicture.FileName);
                appFeilName = model.empName + DateTime.Now.ToString("yymmssfff") + extension;
                string PDFName = appFeilName;
                appFeilName = Path.Combine(Server.MapPath("~/Attachments/"), appFeilName);
                model.empPicture.SaveAs(appFeilName);

                Employee emp = new Employee();
                emp.empID = model.empID;
                emp.UserID = model.UserID;
                emp.empAddress = model.empAddress;
                emp.empBankAccount = model.empBankAccount;
                emp.empDataOfBirth = Convert.ToDateTime(model.empDataOfBirth);
                emp.EmpTId = model.EmpTId;
                emp.empEmergencyPhone = model.empEmergencyPhone;
                emp.empGender = model.empGender;
                emp.empIdentificationNo = model.empIdentificationNo;
                emp.empMaritalStatus = model.empMaritalStatus;
                emp.empName = model.empName;
                emp.empNationality = model.empNationality;
                emp.empPassportNo = model.empPassportNo;
                emp.empPlaceOfBirth = model.empPlaceOfBirth;
                emp.empPrivateAddress = model.empPrivateAddress;
                emp.empPicture = PDFName;
                db.Entry(emp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: HRModule/Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }

UniversityManagementSystem/Areas/HRModule/Views/Employees/Create.cshtml
@model UniversityManagementSystem.Areas.HRModule.Models.EmployeeModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel {
        padding: 10px;
    }
</style>
<div class="panel">


    @using (Html.BeginForm("Create", "Employees", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Create Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.empName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="font-weight:bold">Picture</label>
                <div class="col-md-10">
                    <input multiple type="file" name="empPicture"  class="form-control" accept="image/*" required>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.empGender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.empGender, new SelectList(ViewBag.Gender), "-- Select Gender --",
                            new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.empGender, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empNationality, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empNationality, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empNationality, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empIdentificationNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empIdentificationNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empIdentificationNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empPassportNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empPassportNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empPassportNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empBankAccount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empBankAccount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empBankAccount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empAddress, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.empPrivateAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empPrivateAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empPrivateAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empEmergencyPhone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empEmergencyPhone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empEmergencyPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empDataOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empDataOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empDataOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empPlaceOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empPlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empPlaceOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empMaritalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.empMaritalStatus, new SelectList(ViewBag.SocialStatus), "-- Select Social Status --",
                            new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.empMaritalStatus, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EmpTId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.EmpTId, ViewBag.empType as IEnumerable<SelectListItem>, "-- Seclect Employee Type --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EmpTId, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }) 
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
   
</div>
<script src="~/Areas/RegistrationModule/Scripts/jquery.validate.min.js"></script>
<script src="~/Areas/RegistrationModule/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/RegistrationModule/Custom_JS/datetime/build/jquery.datetimepicker.full.js"></script>

UniversityManagementSystem/Areas/HRModule/Views/Employees/Delete.cshtml
@model UniversityManagementSystem.Models.Employee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.empName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empGender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empGender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empNationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empNationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empIdentificationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empIdentificationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empPassportNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empPassportNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empBankAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empBankAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empPrivateAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empPrivateAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empEmergencyPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empEmergencyPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empDataOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empDataOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empPlaceOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empPlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empMaritalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empMaritalStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManagementSystem/Areas/HRModule/Views/Employees/Details.cshtml
@model UniversityManagementSystem.Models.Employee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .panel {
        padding: 10px;
    }
</style>
<div class="panel">

    <h4>Employee</h4>
    <hr />
    <table class="table table-striped table-bordered dataTable no-footer">
        <tbody>
           <tr>
               <td style="width:20px;">Name</td>
               <td>@Html.DisplayFor(model => model.empName)</td>
           </tr> 
            <tr>
                <td>Email</td>
                <td>@Html.DisplayFor(model => model.AspNetUser.Email)</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>@Html.DisplayFor(model => model.empGender)</td>
            </tr>
            <tr>
                <td>Nationality</td>
                <td>@Html.DisplayFor(model => model.empNationality)</td>
            </tr>
            <tr>
                <td>Identification No</td>
                <td>@Html.DisplayFor(model => model.empIdentificationNo)</td>
            </tr>
            <tr>
                <td>Passport No</td>
                <td>@Html.DisplayFor(model => model.empPassportNo)</td>
            </tr>
            <tr>
                <td>Bank Account</td>
                <td>@Html.DisplayFor(model => model.empBankAccount)</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>@Html.DisplayFor(model => model.empAddress)</td>
            </tr>

            <tr>
                <td>Private Address</td>
                <td>@Html.DisplayFor(model => model.empPrivateAddress)</td>
            </tr>
            <tr>
                <td>Emergency Phone</td>
                <td>@Html.DisplayFor(model => model.empEmergencyPhone)</td>
            </tr>
            <tr>
                <td>Data Of Birth</td>
                <td>@Html.DisplayFor(model => model.empDataOfBirth)</td>
            </tr>
            <tr>
                <td>Place Of Birth</td>
                <td>@Html.DisplayFor(model => model.empPlaceOfBirth)</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>@Html.DisplayFor(model => model.empMaritalStatus)</td>
            </tr>
            <tr>
                <td>Picture</td>
                <td>@Html.DisplayFor(model => model.empPicture)</td>
            </tr>

        </tbody>
    </table>
    
</div>

UniversityManagementSystem/Areas/HRModule/Views/Employees/Index.cshtml
@model IEnumerable<UniversityManagementSystem.Models.Employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel {
        padding: 10px;
    }
</style>
<div class="panel">
    <h2>Index</h2>

    <p>
        <a class="btn btn-primary" href="/HRModule/Employees/Create"><i class="fa fa-plus"></i></a>
    </p>
    <table id="example" class="table table-striped table-bordered" cellspacing="0">
        <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Nationality
                </th>

                <th>
                    Passport No
                </th>


                <th>
                    Private Address
                </th>

                <th>
                    Data Of Birth
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.empName)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.empNationality)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.empPassportNo)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.empPrivateAddress)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.empDataOfBirth)
                    </td>


                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.empID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.empID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.empID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Scripts.Render("~/datatable_plugins/jquery")
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>