UniversityManagementSystem/Areas/AcademicAffairsModule/Controllers/TransferStudentsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Areas.AcademicAffairsModule.Models;
using UniversityManagementSystem.Areas.ResultModule.Models;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Areas.AcademicAffairsModule.Controllers
{
    [Authorize]
    public class TransferStudentsController : Controller
    {
        private UniversityManagementSystemEntities db = new UniversityManagementSystemEntities();
        private string msg;

        // GET: AcademicAffairsModule/TransferStudents
        [HttpGet]
        public ActionResult SetSemester()
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Set Semester";

            DropDown();
            List<GetStudantInfoModel> StdList = new List<GetStudantInfoModel>();
            var data = db.R_StudentRegistration_data.Select(s => new { s.SR_Id, s.Student_Id, Student_FullName = s.R_StudentInfo_data.Student_FullName }).ToList().Take(0);
            foreach (var item in data)
            {
                GetStudantInfoModel row = new GetStudantInfoModel
                {
                    SR_Id = item.SR_Id,
                    StdId = item.Student_Id,
                    StdName = item.Student_FullName
                };
                StdList.Add(row);
            }
            ViewBag.StdInfo = StdList.ToList();
            return View();
        }

        //POST: ResultModule/SemesterResult
        [HttpPost]
        public ActionResult SetSemester(RetSemesterModel search)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Set Semester";

            DropDown();
            List<GetStudantInfoModel> StdList = new List<GetStudantInfoModel>();
            var data = db.Re_StudentResult_data.Where(s => s.R_StudentRegistration_data.Year_Id == search.Year_Id && s.R_StudentRegistration_data.Department_Id == search.Department_Id && s.R_StudentRegistration_data.batch_Id == search.batch_Id && s.R_StudentRegistration_data.Semester_Id == search.Semester_Id).
                Select(s => new { s.SR_Id, s.R_StudentRegistration_data.Student_Id, Student_FullName = s.R_StudentRegistration_data.R_StudentInfo_data.Student_FullName }).ToList();
            foreach (var item in data)
            {
                GetStudantInfoModel row = new GetStudantInfoModel
                {
                    SR_Id = item.SR_Id,
                    StdId = item.Student_Id,
                    StdName = item.Student_FullName
                };
                StdList.Add(row);
            }
            ViewBag.StdInfo = StdList.ToList();
            return View();
        }
        
        // POST: AcademicAffairsModule/TransferStudents
        [HttpPost]
        public JsonResult SetSemesterForStudants(RetSemesterModel data)
        {
            var ChickSemesterType = db.R_Semester_data.Find(data.Semester_Id).Semester_Type;
            if (ChickSemesterType == 2)
            {
                msg = "The operation can not be performed Go to set New Year.";
            }
            else
            {
                foreach (var item in data.StdList)
                {
                    var ResultIsCal = db.Re_StudentResult_data.FirstOrDefault(s => s.SR_Id == item.SR_Id).Result_calculationNumber;
                    if (ResultIsCal == 0)
                    {
                        msg = "The result has not yet been calculated.";
                    }
                    else
                    {
                        var NextSemester = data.Semester_Id + 1;
                        //Get user semester
                        var InSemester = db.R_StudentRegistration_data.Any(s => 
                        s.Year_Id == data.Year_Id && 
                        s.Department_Id == data.Department_Id &&
                        s.batch_Id == data.batch_Id && 
                        s.Semester_Id == NextSemester &&
                        s.Student_Id == item.StdId);

                        if (InSemester == true)
                        {
                            msg = "Student data already exists.";
                        }
                        else
                        {
                            //Get Studant Result number 
                            int ResultId = db.Re_StudentResult_data.FirstOrDefault(s => s.SR_Id == item.SR_Id).Result_Id;
                            R_StudentRegistration_data StdReg = new R_StudentRegistration_data()
                            {
                                Department_Id = data.Department_Id,
                                batch_Id = data.batch_Id,
                                Semester_Id = NextSemester,
                                Year_Id = data.Year_Id,
                                Student_Id = item.StdId,
                                Registered = false,
                                User_Id = User.Identity.GetUserId(),
                                Registr_Status = "Formal",
                            };
                            db.R_StudentRegistration_data.Add(StdReg);
                            db.SaveChanges();
                            msg = "Students of  " + db.R_BatchNumber_data.Find(data.batch_Id).batch_Name + "Batch have been transferred to the new semester  " + NextSemester + " successfully .";
                        }
                    }
                }
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        // GET: AcademicAffairsModule/transfer students to next year
        [HttpGet]
        public JsonResult SetYearForStudants(RetSemesterModel data)
        {
            var ChickSemesterType = db.R_Semester_data.Find(data.Semester_Id).Semester_Type;
            if (ChickSemesterType == 1)
            {
                msg = "The Operation can not be Performed Go to set New Semester.";
            }
            else
            {
                foreach (var item in data.StdList)
                {
                    var ResultIsCal = db.Re_StudentResult_data.FirstOrDefault(s => s.SR_Id == item.SR_Id).Result_calculationNumber;
                    if (ResultIsCal == 0)
                    {
                        msg = "The Result has not yet been Calculated.";
                    }
                    else
                    {
                        //Get Next Year Id
                        var currentYear = db.R_StudyYear_data.Find(data.Year_Id).Year_Number;
                        var NextYear = GetNextYear(currentYear);
                        //Get Next Semester Id
                        var CurrentNumber = db.R_Semester_data.Find(data.Semester_Id).Semester_Number;
                        var NextSemester = db.R_Semester_data.FirstOrDefault(y => y.Semester_Number == CurrentNumber + 1).Semester_Id;
                        //Get Bast Semester Id
                        var BastSemester = db.R_Semester_data.FirstOrDefault(y => y.Semester_Number == CurrentNumber - 1).Semester_Id;
                        //Get Studant Result number 
                        int ResultId = db.Re_StudentResult_data.FirstOrDefault(s => s.SR_Id == item.SR_Id).Result_Id;
                        //Get New Batch Number
                        var CurrentBatch = db.R_BatchNumber_data.FirstOrDefault(b => b.Department_Id == data.Department_Id);
                        //var NewBatch =db.R_BatchNumber_data.FirstOrDefault(b=> b.Department_Id == da)

                        //Get user semester
                        var InSemester = db.R_StudentRegistration_data.Any(s =>
                        s.Year_Id == data.Year_Id &&
                        s.Department_Id == data.Department_Id &&
                        s.batch_Id == data.batch_Id &&
                        s.Semester_Id == NextSemester &&
                        s.Student_Id == item.StdId);

                        if (InSemester == true)
                        {
                            msg = "Student data already exists.";
                        }
                        else
                        {
                            var CumulativePoints = db.Re_StudentResult_data.Find(item.SR_Id).Result_CumulativePoints;
                            if (CumulativePoints >= 2.00)
                            {
                                TransferStudantToNextSemester(item.SR_Id, item.StdId, data.Department_Id, NextYear, NextSemester, data.batch_Id);
                                AcademicStatus(ResultId,"Success");
                            }
                            else
                            if (CumulativePoints > 1.25 && CumulativePoints < 2.00)
                            {
                                int B_Id = NewBatch(NextYear, data.Department_Id);
                                TransferStudantToNextSemester(item.SR_Id, item.StdId, data.Department_Id, NextYear, BastSemester, B_Id);
                                AcademicStatus(ResultId, "Repeat");
                            }
                            else
                            {
                                AcademicStatus(ResultId, "Detained");
                            }
                            msg = "Students of " + db.R_BatchNumber_data.Find(data.batch_Id).batch_Name + " Batch have been transferred to the new Year successfully .";
                        }
                    }
                }
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        // TransferStudents
        public void TransferStudantToNextSemester(int SR_Id, int StdId, int Dept_Id, int YearIdTo, int SemYearIdTo, int batch_Id)
        {
            //Get Studant Result Number 
            int ResultId = db.Re_StudentResult_data.FirstOrDefault(s => s.SR_Id == SR_Id).Result_Id;

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/TransferStudents/SetSemester.cshtml
@using UniversityManagementSystem.Models;
@model UniversityManagementSystem.Areas.AcademicAffairsModule.Models.RetSemesterModel
@{
    ViewBag.Title = "Set Semester & Year";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/asset/css/Custom.css" rel="stylesheet" />
<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_SetSemester {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>
@using (Html.BeginForm("SetSemester", "TransferStudents", new { area = "AcademicAffairsModule" }, FormMethod.Post, new { id = "EnterResultForm" }))
{
    <div class="panel">
        <div class="row">
            <br />
            <div class="col-md-6">
                <div class="form-group" style="padding:3px 0px">
                    <label class="control-label col-md-2"> Year </label>
                    <div class="col-md-10">
                        @Html.DropDownList("Year_Id", (SelectList)ViewBag.Year_Id, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Year_Id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group" style="padding:3px 0px">
                    <label class="control-label col-md-2"> Department </label>
                    <div class="col-md-10">
                       @Html.DropDownList("Department_Id", (SelectList)ViewBag.Department_Id, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Department_Id, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group" style="padding:3px 0px">
                    <label class="control-label col-md-2"> batch </label>
                    <div class="col-md-10">
                        @Html.DropDownList("batch_Id", (SelectList)ViewBag.batch_Id, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.batch_Id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group" style="padding:3px 0px">
                    <label class="control-label col-md-2"> Semester </label>
                    <div class="col-md-10">
                        @Html.DropDownList("Semester_Id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Semester_Id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group" style="padding:5px 0px">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary" style="float:right">get Students</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table id="SetSemester_td" class="table table-striped table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Registration No</th>
                        <th>Student Name</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in ViewBag.StdInfo)
                        {
                            <tr id="@item.StdId">
                                <td>@item.StdId</td>
                                <td data-target="SR_Id">@item.SR_Id</td>
                                <td>@item.StdName</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>

            @*ff*@
            <button type="button" data-toggle="modal" data-target="#Modal_View" class="btn btn-primary">Set Semester</button>
            <div class="modal fade" id="Modal_View" tabindex="-1" role="dialog" aria-labelledby="Modal_ViewLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div id="Loding" class="backgroundLoding">
                            <img id="LodingImg" class="LodingImg" src="~/asset/img/loading.gif" />
                        </div>
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="ModalLabel"></h4>
                        </div>
                        <form id="TSform_data" method="post" enctype="multipart/form-data">
                            <div class="modal-body">
                                <h4>Do you want to transfer students?</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="SetSemesterBtn" class="btn btn-primary">Set Semester</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Reset</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

            @*hh*@
            <button type="button" data-toggle="modal" data-target="#Modal_ViewSetYear" class="btn btn-primary">Set Year</button>
            <div class="modal fade" id="Modal_ViewSetYear" tabindex="-1" role="dialog" aria-labelledby="Modal_ViewLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div id="YLoding" class="backgroundLoding">
                            <img id="LodingImg" class="LodingImg" src="~/asset/img/loading.gif" />
                        </div>
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="ModalLabel"></h4>
                        </div>
                        <form id="TSform_data" method="post" enctype="multipart/form-data">
                            <div class="modal-body">
                                <h4>Do you want to transfer students?</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="SetYearBtn" class="btn btn-primary">Set Year</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Reset</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/datatable_plugins/jquery")
<script src="~/Areas/AcademicAffairsModule/Custom_JS/Data_Table.js"></script>
<script src="~/Areas/AcademicAffairsModule/Custom_JS/AcademicSitting.js"></script>