UniversityManagementSystem/Areas/AcademicAffairsModule/Controllers/AssignToCourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Areas.AcademicAffairsModule.Controllers
{
    [Authorize]
    public class AssignToCourseController : Controller
    {
        private UniversityManagementSystemEntities db = new UniversityManagementSystemEntities();

        // GET: AcademicAffairsModule/AssignToCourse
        public ActionResult Index()
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Assign Data";

            var c_CourseAssignToYear_data = db.C_CourseAssignToYear_data.Include(c => c.C_Courses_data).Include(c => c.C_Teachers_data).Include(c => c.R_Departments_data).Include(c => c.R_Semester_data).Include(c => c.R_StudyYear_data);
            return View(c_CourseAssignToYear_data.ToList());
        }

        // GET: AcademicAffairsModule/AssignToCourse/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "View Assign Data";

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_CourseAssignToYear_data c_CourseAssignToYear_data = db.C_CourseAssignToYear_data.Find(id);
            if (c_CourseAssignToYear_data == null)
            {
                return HttpNotFound();
            }
            return View(c_CourseAssignToYear_data);
        }

        // GET: AcademicAffairsModule/AssignToCourse/Create
        public ActionResult Create()
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Create Assign Data";

            ViewBag.Course_Id = new SelectList(db.C_Courses_data, "Course_Id", "Course_Name");
            ViewBag.Teacher_Id = new SelectList(db.C_Teachers_data, "Teacher_Id", "Teacher_Name");
            ViewBag.Department_Id = new SelectList(db.R_Departments_data, "Department_Id", "Department_Name");
            ViewBag.Semester_Id = new SelectList(db.R_Semester_data, "Semester_Id", "Semester_Name");
            ViewBag.Year_Id = new SelectList(db.R_StudyYear_data, "Year_Id", "Year_Name");
            return View();
        }

        // POST: AcademicAffairsModule/AssignToCourse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CATYId,Course_Id,Year_Id,Department_Id,Semester_Id,Teacher_Id")] C_CourseAssignToYear_data c_CourseAssignToYear_data)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Create Assign Data"; 

            var isExist = db.C_CourseAssignToYear_data.Any(c=> c.Course_Id ==c_CourseAssignToYear_data.Course_Id && 
            c.Year_Id == c_CourseAssignToYear_data.Year_Id && c.Department_Id == c_CourseAssignToYear_data.Department_Id && 
            c.Semester_Id == c_CourseAssignToYear_data.Semester_Id && c.Teacher_Id == c_CourseAssignToYear_data.Teacher_Id);
            if (ModelState.IsValid || isExist == true)
            {
                db.C_CourseAssignToYear_data.Add(c_CourseAssignToYear_data);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Course_Id = new SelectList(db.C_Courses_data, "Course_Id", "Course_Name", c_CourseAssignToYear_data.Course_Id);
            ViewBag.Teacher_Id = new SelectList(db.C_Teachers_data, "Teacher_Id", "Teacher_Name", c_CourseAssignToYear_data.Teacher_Id);
            ViewBag.Department_Id = new SelectList(db.R_Departments_data, "Department_Id", "Department_Name", c_CourseAssignToYear_data.Department_Id);
            ViewBag.Semester_Id = new SelectList(db.R_Semester_data, "Semester_Id", "Semester_Name", c_CourseAssignToYear_data.Semester_Id);
            ViewBag.Year_Id = new SelectList(db.R_StudyYear_data, "Year_Id", "Year_Name", c_CourseAssignToYear_data.Year_Id);
            return View(c_CourseAssignToYear_data);
        }

        // GET: AcademicAffairsModule/AssignToCourse/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Edit Assign Data";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_CourseAssignToYear_data c_CourseAssignToYear_data = db.C_CourseAssignToYear_data.Find(id);
            if (c_CourseAssignToYear_data == null)
            {
                return HttpNotFound();
            }
            ViewBag.Course_Id = new SelectList(db.C_Courses_data, "Course_Id", "Course_Name", c_CourseAssignToYear_data.Course_Id);
            ViewBag.Teacher_Id = new SelectList(db.C_Teachers_data, "Teacher_Id", "Teacher_Name", c_CourseAssignToYear_data.Teacher_Id);
            ViewBag.Department_Id = new SelectList(db.R_Departments_data, "Department_Id", "Department_Name", c_CourseAssignToYear_data.Department_Id);
            ViewBag.Semester_Id = new SelectList(db.R_Semester_data, "Semester_Id", "Semester_Name", c_CourseAssignToYear_data.Semester_Id);
            ViewBag.Year_Id = new SelectList(db.R_StudyYear_data, "Year_Id", "Year_Name", c_CourseAssignToYear_data.Year_Id);
            return View(c_CourseAssignToYear_data);
        }

        // POST: AcademicAffairsModule/AssignToCourse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CATYId,Course_Id,Year_Id,Department_Id,Semester_Id,Teacher_Id")] C_CourseAssignToYear_data c_CourseAssignToYear_data)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Edit Assign Data";

            if (ModelState.IsValid)
            {
                db.Entry(c_CourseAssignToYear_data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Course_Id = new SelectList(db.C_Courses_data, "Course_Id", "Course_Name", c_CourseAssignToYear_data.Course_Id);
            ViewBag.Teacher_Id = new SelectList(db.C_Teachers_data, "Teacher_Id", "Teacher_Name", c_CourseAssignToYear_data.Teacher_Id);
            ViewBag.Department_Id = new SelectList(db.R_Departments_data, "Department_Id", "Department_Name", c_CourseAssignToYear_data.Department_Id);
            ViewBag.Semester_Id = new SelectList(db.R_Semester_data, "Semester_Id", "Semester_Name", c_CourseAssignToYear_data.Semester_Id);
            ViewBag.Year_Id = new SelectList(db.R_StudyYear_data, "Year_Id", "Year_Name", c_CourseAssignToYear_data.Year_Id);
            return View(c_CourseAssignToYear_data);
        }

        // GET: AcademicAffairsModule/AssignToCourse/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Delete Assign Data";

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_CourseAssignToYear_data c_CourseAssignToYear_data = db.C_CourseAssignToYear_data.Find(id);
            if (c_CourseAssignToYear_data == null)
            {
                return HttpNotFound();
            }
            return View(c_CourseAssignToYear_data);
        }

        // POST: AcademicAffairsModule/AssignToCourse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.MainTitle = "Academic Affairs Module";
            ViewBag.SubTitle = "Delete Assign Data";

            C_CourseAssignToYear_data c_CourseAssignToYear_data = db.C_CourseAssignToYear_data.Find(id);
            db.C_CourseAssignToYear_data.Remove(c_CourseAssignToYear_data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/AssignToCourse/Create.cshtml
@model UniversityManagementSystem.Models.C_CourseAssignToYear_data

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_AssignToCourse {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Course Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Course_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Course_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Year_Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Year_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Year_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Department_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Department_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Semester Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Semester_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Semester_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Teacher Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Teacher_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Teacher_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/AssignToCourse/Delete.cshtml
@model UniversityManagementSystem.Models.C_CourseAssignToYear_data

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_AssignToCourse {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Course Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_Courses_data.Course_Name)
        </dd>

        <dt>
            Teacher Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_Teachers_data.Teacher_Name)
        </dd>

        <dt>
            Department Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_Departments_data.Department_Name)
        </dd>

        <dt>
            Semester Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_Semester_data.Semester_Name)
        </dd>

        <dt>
            Year Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_StudyYear_data.Year_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/AssignToCourse/Details.cshtml
@model UniversityManagementSystem.Models.C_CourseAssignToYear_data

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_AssignToCourse {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Course Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_Courses_data.Course_Name)
        </dd>

        <dt>
            Teacher Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_Teachers_data.Teacher_Name)
        </dd>

        <dt>
            Department Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_Departments_data.Department_Name)
        </dd>

        <dt>
            Semester Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_Semester_data.Semester_Name)
        </dd>

        <dt>
            Year Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_StudyYear_data.Year_Name)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CATYId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/AssignToCourse/Edit.cshtml
@model UniversityManagementSystem.Models.C_CourseAssignToYear_data

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_AssignToCourse {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CATYId)

        <div class="form-group">
            @Html.Label("Course Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Course_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Course_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Year Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Year_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Year_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Department_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Department_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Semester Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Semester_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Semester_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Teacher Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Teacher_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Teacher_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UniversityManagementSystem/Areas/AcademicAffairsModule/Views/AssignToCourse/Index.cshtml
@model IEnumerable<UniversityManagementSystem.Models.C_CourseAssignToYear_data>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #left-menu .sub-left-menu #AcademicModule {
        display: block !important;
    }

    #left-menu .sub-left-menu #btn_AssignToCourse {
        background-color: #1c84c6;
        border: solid 1px #1c84c6;
        border-left: none;
        color: white;
        font-size: 1.1em;
    }
</style>
<div class="panel">

    <p>
        <a href="#" class="btn btn-primary" onclick="location.href='@Url.Action("Create" ,"AssignToCourse" , new { area = "AcademicAffairsModule"})'"><i class="fa fa-plus-circle bigger-110 blue"></i></a>
    </p>
    <div class="panel-body">
        <table id="AssignToCourse_datatables" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                       Course Name
                    </th>
                    <th>
                        Teacher Name
                    </th>
                    <th>
                        Department Name
                    </th>
                    <th>
                        Semester Name
                    </th>
                    <th>
                        Year Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.C_Courses_data.Course_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.C_Teachers_data.Teacher_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.R_Departments_data.Department_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.R_Semester_data.Semester_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.R_StudyYear_data.Year_Name)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.CATYId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.CATYId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.CATYId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Scripts.Render("~/datatable_plugins/jquery")
<script src="~/Areas/AcademicAffairsModule/Custom_JS/Data_Table.js"></script>